@extends('front.layout.app')

@section('main_content')

<!-- Top Banner Section for Company Jobs Panel -->
<div class="page-top"
    style="background-image: url('{{ asset('uploads/'.$global_banner_data->banner_company_panel) }}')">
    <div class="bg"></div> <!-- Background overlay for styling -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Page Title (All Jobs) -->
                <h2>All Jobs</h2>
            </div>
        </div>
    </div>
</div>

<!-- Main Content Section -->
<div class="page-content user-panel">
    <div class="container">
        <div class="row">

            <!-- Left Sidebar with Company Navigation Links -->
            <div class="col-lg-3 col-md-12">
                <div class="card">
                    <!-- Include the sidebar for the company panel (typically contains navigation links) -->
                    @include('company.sidebar')
                </div>
            </div>

            <!-- Right Section: Job Listings Table -->
            <div class="col-lg-9 col-md-12">

                <!-- Table that lists all jobs for the company -->
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tbody>
                            <!-- Table Headers for Job Information -->
                            <tr>
                                <th>SL</th> <!-- Serial Number -->
                                <th>Title</th> <!-- Job Title -->
                                <th>Category</th> <!-- Job Category -->
                                <th>Location</th> <!-- Job Location -->
                                <th>Is Featured?</th> <!-- Whether the job is featured or not -->
                                <th>Action</th> <!-- Edit/Delete Actions -->
                            </tr>

                            <!-- Loop through each job and display its information -->
                            @foreach($jobs as $item)
                            <tr>
                                <!-- Serial Number (automatically generated by loop) -->
                                <td>{{ $loop->iteration }}</td>

                                <!-- Job Title -->
                                <td>{{ $item->title }}</td>

                                <!-- Job Category (related to rJobCategory) -->
                                <td>{{ $item->rJobCategory->name }}</td>

                                <!-- Job Location (related to rJobLocation) -->
                                <td>{{ $item->rJobLocation->name }}</td>

                                <!-- Is Featured? (shows badge based on featured status) -->
                                <td>
                                    @if($item->is_featured == 1)
                                    <span class="badge bg-success">Featured</span> <!-- Green badge for Featured -->
                                    @else
                                    <span class="badge bg-danger">Not Featured</span>
                                    <!-- Red badge for Not Featured -->
                                    @endif
                                </td>

                                <!-- Action Buttons: Edit and Delete -->
                                <td>
                                    <!-- Edit button -->
                                    <a href="{{ route('company_jobs_edit', $item->id) }}"
                                        class="btn btn-warning btn-sm text-white">
                                        <i class="fas fa-edit"></i> <!-- Edit icon -->
                                    </a>
                                    <!-- Delete button with confirmation prompt -->
                                    <a href="{{ route('company_jobs_delete', $item->id) }}"
                                        class="btn btn-danger btn-sm" onClick="return confirm('Are you sure?');">
                                        <i class="fas fa-trash-alt"></i> <!-- Delete icon -->
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div> <!-- End of Table -->

            </div>
        </div>
    </div>
</div>

@endsection